config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config
  root 'welcome#index'
  resources :sales
  resources :suppliers
  resources :expenses
  resources :receipts
  resources :shops
  resources :products
  resources :buyers
  resources :providers
  resources :sellers
  resources :reports
  resources :stocks
  devise_for :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/buyer.rb
class Buyer < User
  has_many :receipts
end

app/models/expense.rb
class Expense < ApplicationRecord
  belongs_to :shop
end

app/models/product.rb
class Product < ApplicationRecord
  validates :title, uniqueness: true, presence: true
end

app/models/provider.rb
class Provider < User
  has_many :suppliers
end

app/models/receipt.rb
class Receipt < ApplicationRecord
  belongs_to :shop
  belongs_to :seller
  belongs_to :buyer
end

app/models/sale.rb
# frozen_string_literal: true

class Sale < ApplicationRecord
  belongs_to :shop
  belongs_to :seller
  has_one :receipt
  has_one :supplier
  has_one :buyer
  has_one :product

  validates :product_id, presence: true

  before_save :add_receipt
  after_destroy :delete_receipt

  def add_receipt
    shop = Shop.find(shop_id)
    if !shop.style.eql?('booths') && !shop.style.eql?('shopfront')
      receipt = Receipt.create!(seller_id: seller_id, shop_id: shop_id, product_id: product_id, buyer_id: buyer_id, price: price, sale_id: id)
      self.receipt_id =  receipt.id
    end
  end

  def delete_receipt
    Receipt.find(receipt_id).destroy! unless receipt_id.nil?
  end
end

app/models/seller.rb
class Seller < User
  has_many :receipts
  has_many :sales
end

app/models/shop.rb
class Shop < ApplicationRecord
  has_many :expenses
  has_many :receipts
end

app/models/stock.rb
class Stock < ApplicationRecord
  belongs_to :shop
  belongs_to :product
end

app/models/supplier.rb
class Supplier < ApplicationRecord
  belongs_to :product
  belongs_to :provider
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :set_shop, only: [:show, :edit, :update, :destroy]

  # GET /shops
  # GET /shops.json
  def index
    @shops = Shop.all
  end

  # GET /shops/1
  # GET /shops/1.json
  def show
    @shop = Shop.find(params[:id])
    @seller = Seller.where(shop_id: @shop.id).first
    @sale = Sale.new
    @stocks = Stock.where(shop_id: @shop.id)
  end

  # GET /shops/new
  def new
    @shop = Shop.new
  end

  # GET /shops/1/edit
  def edit
  end

  # POST /shops
  # POST /shops.json
  def create
    @shop = Shop.new(shop_params)

    respond_to do |format|
      if @shop.save
        format.html { redirect_to @shop, notice: 'Shop was successfully created.' }
        format.json { render :show, status: :created, location: @shop }
      else
        format.html { render :new }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shops/1
  # PATCH/PUT /shops/1.json
  def update
    respond_to do |format|
      if @shop.update(shop_params)
        format.html { redirect_to @shop, notice: 'Shop was successfully updated.' }
        format.json { render :show, status: :ok, location: @shop }
      else
        format.html { render :edit }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shops/1
  # DELETE /shops/1.json
  def destroy
    @shop.destroy
    respond_to do |format|
      format.html { redirect_to shops_url, notice: 'Shop was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shop
      @shop = Shop.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shop_params
      params.fetch(:shop, {})
    end
end

app/helpers/buyers_helper.rb
module BuyersHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/receipts_helper.rb
module ReceiptsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/sellers_helper.rb
module SellersHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/shops/_form.html.haml
= form_for @shop do |f|
  - if @shop.errors.any?
    #error_explanation
      %h2= "#{pluralize(@shop.errors.count, "error")} prohibited this shop from being saved:"
      %ul
        - @shop.errors.full_messages.each do |message|
          %li= message

  .actions
    = f.submit 'Save'

app/views/shops/edit.html.haml
%h1 Editing shop

= render 'form'

= link_to 'Show', @shop
\|
= link_to 'Back', shops_path

app/views/shops/index.html.haml
.shops
  .container
    .row
      .col-sm
        %h1 shops
    .row
      .col-sm
        - @shops.each do |shop|
          .card.mb-3
            .card-body
              = link_to "Shop # #{shop.id}", shop, class: 'btn btn-dark'

app/views/shops/new.html.haml
%h1 New shop

= render 'form'

= link_to 'Back', shops_path

app/views/shops/show.html.haml
.shops
  .container
    .row
      .col-sm
        %h1 shop # #{@shop.id}
    .row
      .col-sm
        - @stocks.each do |stock|
          .card.mb-3
            .card-title
              .text-center
                %h5= stock.product.title
            .card-body
              %b="#{(stock.price * 1.25).to_i}$"
            .card-footer
              =form_for Sale.new, :remote => true do |f|
                .field
                  = f.hidden_field :shop_id, value: @shop.id
                  = f.hidden_field :buyer_id, value: current_user.id
                  = f.hidden_field :product_id, value: stock.product.id
                .action
                  = f.submit "Buy", class: "btn btn-outline-success"