config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config
  root 'welcome#index'
  resources :sales
  resources :suppliers
  resources :expenses
  resources :receipts
  resources :shops
  resources :products
  resources :buyers
  resources :providers
  resources :sellers
  resources :reports
  resources :stocks
  devise_for :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/buyer.rb
class Buyer < User
  has_many :receipts
end

app/models/expense.rb
class Expense < ApplicationRecord
  belongs_to :shop
end

app/models/product.rb
class Product < ApplicationRecord
  validates :title, uniqueness: true, presence: true
end

app/models/provider.rb
class Provider < User
  has_many :suppliers
end

app/models/receipt.rb
class Receipt < ApplicationRecord
  belongs_to :shop
  belongs_to :seller
  belongs_to :buyer
end

app/models/sale.rb
# frozen_string_literal: true

class Sale < ApplicationRecord
  belongs_to :shop
  belongs_to :seller
  has_one :receipt
  has_one :supplier
  has_one :buyer
  has_one :product

  validates :product_id, presence: true

  before_save :add_receipt
  after_destroy :delete_receipt

  def add_receipt
    shop = Shop.find(shop_id)
    if !shop.style.eql?('booths') && !shop.style.eql?('shopfront')
      receipt = Receipt.create!(seller_id: seller_id, shop_id: shop_id, product_id: product_id, buyer_id: buyer_id, price: price, sale_id: id)
      self.receipt_id =  receipt.id
    end
  end

  def delete_receipt
    Receipt.find(receipt_id).destroy! unless receipt_id.nil?
  end
end

app/models/seller.rb
class Seller < User
  has_many :receipts
  has_many :sales
end

app/models/shop.rb
class Shop < ApplicationRecord
  has_many :expenses
  has_many :receipts
end

app/models/stock.rb
class Stock < ApplicationRecord
  belongs_to :shop
  belongs_to :product
end

app/models/supplier.rb
class Supplier < ApplicationRecord
  belongs_to :product
  belongs_to :provider
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/sales_controller.rb
# frozen_string_literal: true

class SalesController < ApplicationController
  before_action :authenticate_user!
  before_action :sale_params, except: %w[index new destroy]
  before_action :check_user
  before_action :prepare
  before_action :set_sale, only: %i[show edit update destroy]

  # GET /sales
  # GET /sales.json
  def index
    @sales = Sale.where(shop_id: current_user.shop_id).order('created_at DESC').page(params[:page]).per(25)
    @shop = @sales.first.shop
  end

  # GET /sales/new
  def new
    @sale = Sale.new
  end

  # POST /sales
  # POST /sales.json
  def create
    if current_user.is_a? Seller
      @sale = Sale.new(sale_params)
      @sale.shop_id = current_user.shop_id
      stock = Stock.where(shop_id: current_user.shop_id, product_id: sale_params[:product_id]).first
      @sale.price = stock.price * 1.25
      respond_to do |format|
        if @sale.save
          if stock.count == 1
            stock.destroy!
          else
            stock.count = stock.count - 1
            stock.save!
          end
          format.html { redirect_to sales_path, success: 'Sale was successfully created.' }
          format.json { render :show, status: :created, location: @sale }
        else
          format.html { render :new }
          format.json { render json: @sale.errors, status: :unprocessable_entity }
        end
      end
    else
      @shop = Shop.find(sale_params[:shop_id])
      @sale = Sale.new(sale_params)
      stock = Stock.where(shop_id: sale_params[:shop_id], product_id: sale_params[:product_id]).first
      @sale.price = stock.price * 1.25
      @sale.seller_id = Seller.where(shop_id: sale_params[:shop_id]).first.id
      respond_to do |format|
        if @sale.save!
          if stock.count == 1
            stock.destroy!
          else
            stock.count = stock.count - 1
            stock.save!
          end
          format.js {}
        else
          format.js {}
        end
      end
    end
  end


  # DELETE /sales/1
  # DELETE /sales/1.json
  def destroy
    sale = Sale.find(params[:id])
    if sale.destroy!
      redirect_to sales_path, success: 'Sale was successfully destroyed.'
    else
      render :index, danger: 'Sale was not destroyed.'
    end
  end

  private

  def prepare
    if current_user.is_a? Seller
      @products = Stock.where(shop_id: current_user.shop_id).map(&:product)
      shop = Shop.find(current_user.shop_id)
      if !shop.style.eql?('booths') && !shop.style.eql?('shopfront')
        @shop = shop
        @buyers = Buyer.all
      end
    end
  end

  def check_user
    #redirect_to root_path unless current_user.is_a? Seller
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_sale
    @sale = Sale.find(params[:id])
  end



  # Never trust parameters from the scary internet, only allow the white list through.
  def sale_params
    if current_user.is_a? Seller
      shop = Shop.find(current_user.shop_id)
      if shop.style.eql?('booths') || shop.style.eql?('shopfront')
        params.require(:sale).permit(:product_id, :seller_id)
      else
        params.require(:sale).permit(:product_id, :seller_id, :buyer_id)
      end
    else
      params.require(:sale).permit(:product_id, :shop_id, :buyer_id)
    end
  end
end

app/helpers/buyers_helper.rb
module BuyersHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/receipts_helper.rb
module ReceiptsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/sellers_helper.rb
module SellersHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/sales/_form.html.haml
= form_for @sale do |f|
  - if @sale.errors.any?
    #error_explanation
      %h2= "#{pluralize(@sale.errors.count, "error")} prohibited this sale from being saved:"
      %ul
        - @sale.errors.full_messages.each do |message|
          %li= message

  .actions
    = f.submit 'Save'

app/views/sales/_sale.html.haml
.sale-card
  .card.mb-3
    .card-header
      %h2
        =seller
    .card-body
      %h3
        = Product.find(product_id).title
      -#  this is really shit, but very-very hot fix
      %h6
        #{price}$
    .card-footer
      %p
        =created_at.strftime("%d/%m/%Y %H:%M")
      = link_to 'Delete', sale_path(id), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-outline-dark'

app/views/sales/create.js.erb
$(window.location.replace("<%= shop_path(@shop.id) %>"))

app/views/sales/edit.html.haml
%h1 Editing sale

= render 'form'

= link_to 'Show', @sale
\|
= link_to 'Back', sales_path

app/views/sales/index.html.haml
.sales
  .container
    .row
      .col-sm
        %h1 Sales at shop # #{@shop.id}
    .row
      .col-sm
        - @sales.each do |sale|
          = render 'sales/sale', id: sale.id, seller: sale.seller.name, product_id: sale.product_id, price: sale.price, created_at: sale.created_at

    .sales-footer
    = paginate @sales

app/views/sales/new.html.haml
.sales
  .new-sale
    .container
      = form_for @sale, html: { multipart: true } do |f|
        .field
          = f.hidden_field :seller_id, value: current_user.id
          = f.label 'Product'
          = f.collection_select :product_id, @products, :id, :title, include_blank: true, class: "dropdown-menu"
          - if @shop
            = f.label 'Buyer'
            = f.collection_select :buyer_id, @buyers, :id, :name, include_blank: true, class: "dropdown-menu"
        .actions
          = f.button 'Create', class: 'btn btn-outline-dark fa fa-shopping-cart'

app/views/sales/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_sale_path(@sale)
\|
= link_to 'Back', sales_path